# Generated by Django 4.2.1 on 2023-05-07 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Railway', '0003_auto_20201010_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='ArrivalTime',
            field=models.TimeField(default='06:00'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='DepartureTime',
            field=models.TimeField(default='18:00'),
        ),
    ]
