# Generated by Django 4.2.1 on 2023-05-07 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Railway', '0004_alter_schedule_arrivaltime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='ArrivalTime_t',
            field=models.TimeField(default='06:00'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='DepartureTime_t',
            field=models.TimeField(default='18:00'),
        ),
    ]
