# Generated by Django 4.2.1 on 2023-05-07 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Railway', '0005_schedule_arrivaltime_t_schedule_departuretime_t'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='ArrivalTime_t',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='DepartureTime_t',
        ),
    ]
